"""Training run orchestration for prematch classifiers (UPDATE plan stage 10, Задача 66).

Wires dataset loading, per-season splits, model training, calibration, the Elo
benchmark, metrics, bootstrap, artifacts, and reports into one reproducible pipeline.
No PostgreSQL or ``modeling.dataset_builder`` imports.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence, cast

import joblib
import numpy as np
import pandas as pd

from modeling.artifacts import (
    _collect_library_versions,
    _get_git_commit,
    build_lgbm_metadata,
    build_logreg_metadata,
    save_model_artifact,
)
from modeling.bootstrap import bootstrap_mean_diff, bootstrap_metrics, standard_metric_fns
from modeling.calibrate import (
    CalibratorFit,
    apply_calibrator,
    fit_calibrator,
    save_calibration_artifact,
)
from modeling.config import ConfigError, ResolvedConfig, SplitConfig, build_run_id
from modeling.elo import (
    EloBenchmark,
    EloHistory,
    elo_season_predictions,
    expand_elo_grid,
    fit_elo_benchmark,
)
from modeling.metrics import (
    brier,
    ece,
    log_loss,
    log_loss_per_game,
    reliability_table,
    team_breakdown,
    trivial_baseline,
)
from modeling.acceptance import (
    RunStatus,
    apply_acceptance_to_training_outcomes,
    apply_latest_symlink_check,
)
from modeling.report import compose_metrics_json, compose_summary_md, configure_run_logger, write_report
from modeling.splits import SeasonSplits, SeasonWindow, build_season_splits
from modeling.train_common import build_monotone_constraints, expand_lgbm_grid, get_task_label, predict_raw_proba
from modeling.train_input import load_training_table_split
from modeling.train_lgbm import (
    LgbmFitResult,
    build_lgbm_base_params,
    select_lgbm_config_by_inner_val,
    train_lgbm_for_task,
    train_lgbm_fixed_rounds,
)
from modeling.train_logreg import FitResult, build_logreg_pipeline, select_C_by_inner_val, train_logreg_for_task

logger = logging.getLogger(__name__)

TASK_NAMES: tuple[str, ...] = ("home_win", "over_5_5")
MODEL_FAMILIES: tuple[str, ...] = ("logreg", "lgbm")

LGBM_NUM_BOOST_ROUND = 500
LGBM_EARLY_STOPPING_ROUNDS = 50


@dataclass(frozen=True)
class BlockSizes:
    train: int
    inner_val: int
    calibration: int
    test: int

    def to_log_dict(self) -> dict[str, int]:
        return {
            "train": self.train,
            "inner_val": self.inner_val,
            "calibration": self.calibration,
            "test": self.test,
        }


@dataclass(frozen=True)
class FinalRetrainSlices:
    train_full_idx: np.ndarray
    inner_val_idx: np.ndarray
    calibration_final_idx: np.ndarray
    train_full_days: tuple[str, str]
    inner_val_days: tuple[str, str]
    calibration_final_days: tuple[str, str]

    @property
    def train_hp_idx(self) -> np.ndarray:
        if len(self.inner_val_idx) == 0:
            return self.train_full_idx
        cutoff = int(self.inner_val_idx[0])
        return self.train_full_idx[self.train_full_idx < cutoff]


@dataclass
class RunResult:
    run_id: str
    task: str
    model: str
    status: RunStatus
    exit_code: int
    reports_dir: Path
    model_run_dir: Path
    pooled_log_loss: float | None = None


@dataclass
class _TaskModelOutcome:
    task: str
    model: str
    result: RunResult
    pooled_model_log_loss: float
    benchmark_log_loss: float
    benchmark: str


def resolve_tasks(task_flag: str, config: ResolvedConfig) -> list[str]:
    """Map CLI ``--task`` to enabled task names."""
    if task_flag not in (*TASK_NAMES, "both"):
        raise ConfigError(f"unsupported --task {task_flag!r}")
    if task_flag == "both":
        selected = [name for name in TASK_NAMES if getattr(config.tasks, name).enabled]
        if not selected:
            raise ConfigError("no tasks enabled in config")
        return selected
    if not getattr(config.tasks, task_flag).enabled:
        raise ConfigError(
            f"task {task_flag!r} is disabled in config (tasks.{task_flag}.enabled=false) "
            f"but was requested via --task"
        )
    return [task_flag]


def resolve_models(model_flag: str) -> list[str]:
    """Map CLI ``--model`` to model family names."""
    if model_flag not in (*MODEL_FAMILIES, "both"):
        raise ConfigError(f"unsupported --model {model_flag!r}")
    if model_flag == "both":
        return list(MODEL_FAMILIES)
    return [model_flag]


def resolve_run_id(
    *,
    task: str,
    model: str,
    features_hash: str,
    run_start_utc: datetime,
    override: str | None,
) -> str:
    """Return explicit ``--run-id`` or canonical autogenerated id."""
    if override is not None:
        return override
    return build_run_id(task, model, features_hash, run_start_utc)


def validate_run_id_override(
    tasks: Sequence[str],
    models: Sequence[str],
    run_id: str | None,
) -> None:
    """Reject a single ``--run-id`` when it would collide across multiple pairs."""
    if run_id is None:
        return
    pairs = len(tasks) * len(models)
    if pairs > 1:
        raise ConfigError(
            f"--run-id {run_id!r} would be reused for {pairs} (task, model) pairs "
            f"({list(tasks)} × {list(models)}); omit --run-id or restrict "
            f"--task / --model to a single pair"
        )


def _sort_frames(
    X: pd.DataFrame,
    keys: pd.DataFrame,
    labels: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    order = keys.sort_values(["day", "game_id"], kind="mergesort").index
    return (
        X.loc[order].reset_index(drop=True),
        keys.loc[order].reset_index(drop=True),
        labels.loc[order].reset_index(drop=True),
    )


def _day_range_iso(keys: pd.DataFrame, idx: np.ndarray) -> tuple[str, str]:
    if len(idx) == 0:
        return ("", "")
    days = pd.to_datetime(keys.iloc[idx]["day"])
    return (days.min().date().isoformat(), days.max().date().isoformat())


def compute_final_retrain_slices(
    keys: pd.DataFrame,
    config: SplitConfig,
) -> FinalRetrainSlices:
    """Derive ``train_full``, ``inner_val`` and ``calibration_final`` for the final model.

    The final model sees every row: ``calibration_final`` is the last ``calibration_games``
    rows, ``train_full`` everything before it, ``inner_val`` the tail of ``train_full``.
    """
    positions = np.arange(len(keys))
    if len(positions) < config.calibration_games:
        raise ConfigError(
            "not enough rows for calibration_final "
            f"(need {config.calibration_games}, have {len(positions)})"
        )

    calibration_final = positions[-config.calibration_games :]
    train_full = positions[: int(calibration_final[0])]

    if len(train_full) == 0:
        raise ConfigError("train_full is empty after carving calibration_final")

    need_inner = config.inner_val_games
    if len(train_full) < need_inner:
        raise ConfigError(
            "not enough rows in train_full for inner_val_final "
            f"(need {need_inner}, have {len(train_full)})"
        )
    inner_val = train_full[-need_inner:]
    return FinalRetrainSlices(
        train_full_idx=train_full,
        inner_val_idx=inner_val,
        calibration_final_idx=calibration_final,
        train_full_days=_day_range_iso(keys, train_full),
        inner_val_days=_day_range_iso(keys, inner_val),
        calibration_final_days=_day_range_iso(keys, calibration_final),
    )


def collect_block_sizes(
    splits: SeasonSplits,
    final_slices: FinalRetrainSlices,
) -> dict[str, Any]:
    """Structured sizes for dry-run logging."""
    season_sizes = [
        {
            "season_id": window.season_id,
            **BlockSizes(
                train=window.train_size,
                inner_val=window.inner_val_size,
                calibration=window.calibration_size,
                test=window.test_size,
            ).to_log_dict(),
        }
        for window in splits.windows
    ]
    final_block = BlockSizes(
        train=len(final_slices.train_full_idx),
        inner_val=len(final_slices.inner_val_idx),
        calibration=len(final_slices.calibration_final_idx),
        test=0,
    )
    return {"seasons": season_sizes, "final_retrain": final_block.to_log_dict()}


def dry_run_training(
    config: ResolvedConfig,
    *,
    dataset_csv: Path,
    metadata_path: Path,
    task_flag: str = "both",
    model_flag: str = "both",
) -> dict[str, Any]:
    """Load data, build splits, return resolved config and block sizes (no training)."""
    _X, keys, _labels, _service, metadata = load_training_table_split(dataset_csv, metadata_path)
    _X, keys, _labels = _sort_frames(_X, keys, _labels)
    splits = build_season_splits(
        keys,
        config.split,
        yaml_reference=config.model_dump(by_alias=True),
        metadata=metadata,
    )
    final_slices = compute_final_retrain_slices(keys, config.split)
    tasks = resolve_tasks(task_flag, config)
    models = resolve_models(model_flag)
    return {
        "config": config.model_dump(by_alias=True),
        "tasks": tasks,
        "models": models,
        "block_sizes": collect_block_sizes(splits, final_slices),
        "splits_log": splits.to_log_dict(),
        "final_retrain_days": {
            "train_full": final_slices.train_full_days,
            "inner_val": final_slices.inner_val_days,
            "calibration_final": final_slices.calibration_final_days,
        },
    }


# Slices of the checked seasons (Задача 66): the first 10% of each season's games, and the
# two weeks after the 2025/26 Olympic break (no NHL games 2026-02-05 ... 2026-02-25).
_SEASON_START_FRACTION = 0.10
_POST_OLYMPIC_SEASON = 20252026
_POST_OLYMPIC_DAYS = ("2026-02-26", "2026-03-11")
# min(home, away) prior games of the season, to choose the ``--min-prior-games`` cut-off.
_PRIOR_GAMES_BUCKETS: tuple[tuple[str, int, int | None], ...] = (
    ("<=7", 0, 7),
    ("8-10", 8, 10),
    ("11-20", 11, 20),
    ("21+", 21, None),
)
_CALIBRATION_TABLE_BINS = 20  # 5 percentage points


@dataclass
class _EloSeason:
    """Elo benchmark for one checked season: chosen curve, forecasts by game, full-season metrics."""

    benchmark: EloBenchmark
    predictions: pd.DataFrame
    full_season: dict[str, Any]


@dataclass
class _SeasonEval:
    """Predictions of one per-season run on all rows of its checked season."""

    window: SeasonWindow
    y: np.ndarray
    p_raw: np.ndarray
    p_cal: np.ndarray
    p_const: np.ndarray
    p_elo_raw: np.ndarray | None
    p_elo: np.ndarray | None
    elo: _EloSeason | None


def _metrics(y: np.ndarray, p: np.ndarray, *, epsilon: float, ece_bins: int) -> dict[str, float]:
    return {
        "log_loss": log_loss(y, p, epsilon=epsilon),
        "brier": brier(y, p),
        "ece": ece(y, p, n_bins=ece_bins),
    }


def _fit_elo_seasons(games_csv: Path, config: ResolvedConfig) -> dict[int, _EloSeason]:
    """Run the Elo benchmark once per checked season from ``games_train.csv`` (all played games)."""
    if not games_csv.is_file():
        raise ConfigError(
            f"{games_csv} not found: the Elo benchmark needs every played game; "
            "rebuild with `python -m modeling.cli build-dataset --mode train`"
        )
    epsilon = config.evaluation.epsilon_clip
    history = EloHistory(pd.read_csv(games_csv))
    grid = expand_elo_grid(config.elo.grid.model_dump())
    out: dict[int, _EloSeason] = {}
    for season_id in config.split.test_seasons:
        benchmark = fit_elo_benchmark(history, season_id, grid, epsilon=epsilon)
        predictions = elo_season_predictions(history, benchmark)
        y = predictions["home_win"].to_numpy()
        full_season = {
            "n_games": int(len(predictions)),
            "elo": _metrics(y, predictions["p_fitted"].to_numpy(), epsilon=epsilon, ece_bins=config.evaluation.ece_bins),
            "elo_raw": _metrics(y, predictions["p_raw"].to_numpy(), epsilon=epsilon, ece_bins=config.evaluation.ece_bins),
        }
        out[season_id] = _EloSeason(benchmark, predictions.set_index("game_id"), full_season)
        logger.info("Elo benchmark season %d: %s", season_id, benchmark.to_dict())
    return out


def _elo_forecasts(elo: _EloSeason, game_ids: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Elo ``(p_raw, p_fitted)`` for the dataset rows of a season; fails on any game Elo lacks."""
    rows = elo.predictions.loc[game_ids]
    if not np.array_equal(rows["home_win"].to_numpy(), y):
        raise ValueError("Elo home-win outcomes disagree with the dataset labels: games_train.csv is stale")
    return rows["p_raw"].to_numpy(), rows["p_fitted"].to_numpy()


def _season_block(ev: _SeasonEval, keys: pd.DataFrame, *, epsilon: float, ece_bins: int) -> dict[str, Any]:
    """``metrics.json`` entry of one checked season."""
    window = ev.window
    block: dict[str, Any] = {
        "season_id": window.season_id,
        "n_train": window.train_size + window.inner_val_size + window.calibration_size,
        "n_test": window.test_size,
        "test_range": dict(zip(("start", "end"), _day_range_iso(keys, window.test_idx))),
        "model_raw": _metrics(ev.y, ev.p_raw, epsilon=epsilon, ece_bins=ece_bins),
        "model": _metrics(ev.y, ev.p_cal, epsilon=epsilon, ece_bins=ece_bins),
        "constant": {"p": float(ev.p_const[0]), **_metrics(ev.y, ev.p_const, epsilon=epsilon, ece_bins=ece_bins)},
    }
    if ev.elo is not None and ev.p_elo is not None and ev.p_elo_raw is not None:
        block["elo_raw"] = _metrics(ev.y, ev.p_elo_raw, epsilon=epsilon, ece_bins=ece_bins)
        block["elo"] = _metrics(ev.y, ev.p_elo, epsilon=epsilon, ece_bins=ece_bins)
        block["elo_params"] = ev.elo.benchmark.to_dict()
        block["elo_full_season"] = ev.elo.full_season
    return block


def _nonempty_bins(y: np.ndarray, p: np.ndarray) -> list[dict[str, Any]]:
    table = reliability_table(y, p, n_bins=_CALIBRATION_TABLE_BINS)
    table = table[table["count"] > 0].drop(columns=["weight"])
    return cast("list[dict[str, Any]]", table.to_dict(orient="records"))


def _slice_masks(evs: Sequence[_SeasonEval], keys: pd.DataFrame, X: pd.DataFrame) -> dict[str, np.ndarray]:
    """Boolean masks over the pooled checked rows for the report slices."""
    test_idx = np.concatenate([ev.window.test_idx for ev in evs])
    season = np.concatenate([np.full(len(ev.y), ev.window.season_id) for ev in evs])
    days = pd.to_datetime(keys.iloc[test_idx]["day"]).to_numpy()
    start = np.concatenate(
        [np.arange(len(ev.y)) < max(1, int(np.ceil(_SEASON_START_FRACTION * len(ev.y)))) for ev in evs]
    )
    lo, hi = (np.datetime64(day) for day in _POST_OLYMPIC_DAYS)
    masks = {
        "season_start": start,
        "post_olympic_break": (season == _POST_OLYMPIC_SEASON) & (days >= lo) & (days <= hi),
    }
    missing = {"home_prior_games_count", "away_prior_games_count"} - set(X.columns)
    if missing:
        raise ConfigError(f"feature matrix lacks {sorted(missing)}: needed for the prior_games report slices")
    prior = np.minimum(
        X["home_prior_games_count"].to_numpy()[test_idx], X["away_prior_games_count"].to_numpy()[test_idx]
    )
    for label, low, high in _PRIOR_GAMES_BUCKETS:
        upper = np.ones(len(prior), dtype=bool) if high is None else prior <= high
        masks[f"prior_games_{label}"] = (prior >= low) & upper
    return masks


def _slice_blocks(
    masks: Mapping[str, np.ndarray],
    y: np.ndarray,
    p_cal: np.ndarray,
    p_const: np.ndarray,
    p_elo: np.ndarray | None,
    *,
    epsilon: float,
) -> dict[str, dict[str, Any]]:
    """Per-slice ``n`` and log-loss of the model, constant and (home_win) Elo; empty slices keep only ``n``."""
    out: dict[str, dict[str, Any]] = {}
    for name, mask in masks.items():
        block: dict[str, Any] = {"n": int(mask.sum())}
        if block["n"] > 0:
            block["model_log_loss"] = log_loss(y[mask], p_cal[mask], epsilon=epsilon)
            block["constant_log_loss"] = log_loss(y[mask], p_const[mask], epsilon=epsilon)
            if p_elo is not None:
                block["elo_log_loss"] = log_loss(y[mask], p_elo[mask], epsilon=epsilon)
        out[name] = block
    return out


def _train_raw_model(
    model_family: str,
    task: str,
    X_train: pd.DataFrame,
    y_train: np.ndarray,
    X_val: pd.DataFrame,
    y_val: np.ndarray,
    config: ResolvedConfig,
    *,
    feature_names: list[str],
    log_loss_fn: Any,
) -> FitResult | LgbmFitResult:
    seed = config.random_seed
    if model_family == "logreg":
        return train_logreg_for_task(
            task,
            X_train,
            y_train,
            X_val,
            y_val,
            C_grid=list(config.models.logreg.grids.C),
            random_seed=seed,
            log_loss_fn=log_loss_fn,
        )
    monotone_spec = getattr(config.models.lgbm.monotone, task)
    monotone = build_monotone_constraints(feature_names, monotone_spec)
    grid = expand_lgbm_grid(config.models.lgbm.grids.model_dump())
    return train_lgbm_for_task(
        task,
        X_train,
        y_train,
        X_val,
        y_val,
        grid=grid,
        random_seed=seed,
        num_threads=config.compute.num_threads,
        early_stopping_rounds=LGBM_EARLY_STOPPING_ROUNDS,
        num_boost_round=LGBM_NUM_BOOST_ROUND,
        log_loss_fn=log_loss_fn,
        monotone_constraints=monotone,
    )


def _raw_model_from_fit(model_family: str, fit: FitResult | LgbmFitResult) -> Any:
    if model_family == "logreg":
        assert isinstance(fit, FitResult)
        return fit.pipeline
    assert isinstance(fit, LgbmFitResult)
    return fit.booster


def _build_season_metadata(
    *,
    model_family: str,
    task: str,
    fit: FitResult | LgbmFitResult,
    config: ResolvedConfig,
    window: SeasonWindow,
    calibrator_fit: CalibratorFit,
    run_id: str,
) -> dict[str, Any]:
    train_days = (
        window.train_days.min_day.date().isoformat(),
        window.train_days.max_day.date().isoformat(),
    )
    inner_days = (
        window.inner_val_days.min_day.date().isoformat(),
        window.inner_val_days.max_day.date().isoformat(),
    )
    cal_days = (
        window.calibration_days.min_day.date().isoformat(),
        window.calibration_days.max_day.date().isoformat(),
    )
    common = {
        "run_id": run_id,
        "task": task,
        "season_id": window.season_id,
        "random_seed": config.random_seed,
        "features_hash": config.features_hash,
        "feature_set_version": config.feature_set_version,
        "feature_manifest": config.feature_manifest,
        "train_days": {"min": train_days[0], "max": train_days[1]},
        "inner_val_days": {"min": inner_days[0], "max": inner_days[1]},
        "calibration_days": {"min": cal_days[0], "max": cal_days[1]},
        "n_rows_train": fit.n_rows_train,
        "n_rows_inner_val": fit.n_rows_inner_val,
        "n_rows_calibration": calibrator_fit.n_calibration,
    }
    if model_family == "logreg":
        assert isinstance(fit, FitResult)
        meta = build_logreg_metadata(
            task=task,
            chosen_C=fit.chosen_C,
            class_weight=None,
            random_seed=config.random_seed,
            features_hash=config.features_hash,
            feature_set_version=config.feature_set_version,
            feature_manifest=config.feature_manifest,
            n_rows_train=fit.n_rows_train,
            n_rows_inner_val=fit.n_rows_inner_val,
            train_days=train_days,
            inner_val_days=inner_days,
            calibration_days=cal_days,
            run_id=run_id,
        )
    else:
        assert isinstance(fit, LgbmFitResult)
        meta = build_lgbm_metadata(
            task=task,
            chosen_params=fit.chosen_params,
            best_iteration=fit.best_iteration,
            random_seed=config.random_seed,
            features_hash=config.features_hash,
            feature_set_version=config.feature_set_version,
            feature_manifest=config.feature_manifest,
            n_rows_train=fit.n_rows_train,
            n_rows_inner_val=fit.n_rows_inner_val,
            train_days=train_days,
            inner_val_days=inner_days,
            calibration_days=cal_days,
            run_id=run_id,
        )
    meta.update(common)
    meta["model_family"] = model_family
    return meta


def _build_final_metadata(
    *,
    model_family: str,
    task: str,
    fit: FitResult | LgbmFitResult,
    config: ResolvedConfig,
    final_slices: FinalRetrainSlices,
    calibrator_fit: CalibratorFit,
    run_id: str,
    status: RunStatus,
    bootstrap_meta: dict[str, Any],
) -> dict[str, Any]:
    train_days = final_slices.train_full_days
    inner_days = final_slices.inner_val_days
    cal_days = final_slices.calibration_final_days
    meta: dict[str, Any] = {
        "run_id": run_id,
        "task": task,
        "model_family": model_family,
        "status": status,
        "random_seed": config.random_seed,
        "features_hash": config.features_hash,
        "feature_set_version": config.feature_set_version,
        "feature_manifest": config.feature_manifest,
        "train_days": {"min": train_days[0], "max": train_days[1]},
        "inner_val_days": {"min": inner_days[0], "max": inner_days[1]},
        "calibration_days": {"min": cal_days[0], "max": cal_days[1]},
        "test_seasons": list(config.split.test_seasons),
        "n_rows_train": len(final_slices.train_full_idx),
        "n_rows_inner_val": len(final_slices.inner_val_idx),
        "n_rows_calibration": calibrator_fit.n_calibration,
        "bootstrap": bootstrap_meta,
        "library_versions": _collect_library_versions(),
        "git_commit": _get_git_commit(),
    }
    if model_family == "logreg":
        assert isinstance(fit, FitResult)
        meta["chosen_C"] = fit.chosen_C
        meta["class_weight"] = None
    else:
        assert isinstance(fit, LgbmFitResult)
        meta["chosen_params"] = fit.chosen_params
        meta["best_iteration"] = fit.best_iteration
    meta.update(calibrator_fit.to_dict())
    return meta


def _team_breakdown_or_empty(
    y_true: np.ndarray,
    p_eval: np.ndarray,
    keys: pd.DataFrame,
    *,
    epsilon: float,
) -> dict[str, list[dict[str, Any]] | pd.DataFrame]:
    out: dict[str, list[dict[str, Any]] | pd.DataFrame] = {}
    for col in ("home_team_id", "away_team_id"):
        if col not in keys.columns:
            out[col] = []
            continue
        frame = team_breakdown(
            y_true,
            p_eval,
            team_ids=keys[col].to_numpy(),
            by=col,  # type: ignore[arg-type]
            epsilon=epsilon,
        )
        out[col] = frame
    return out


def update_latest_symlink(
    task: str,
    model: str,
    run_id: str,
    *,
    artifacts_root: Path,
    status: RunStatus,
) -> None:
    """Atomically point ``artifacts/models/<task>/<model>/latest`` at ``<run_id>/final/``.

    Skipped when ``status != ok``. On filesystems without symlink support, writes
    ``latest.txt`` with the relative target path instead of raising.
    """
    if status != "ok":
        logger.info(
            "Skipping latest symlink for %s/%s run %s (status=%s)",
            task,
            model,
            run_id,
            status,
        )
        return

    base = artifacts_root / "models" / task / model
    base.mkdir(parents=True, exist_ok=True)
    rel_target = Path(run_id) / "final"
    link_path = base / "latest"
    tmp_link = base / f".latest_tmp_{run_id}"

    try:
        if tmp_link.exists() or tmp_link.is_symlink():
            tmp_link.unlink()
        os.symlink(rel_target, tmp_link)
        os.replace(tmp_link, link_path)
        logger.info("Updated latest symlink → %s", rel_target)
    except OSError as exc:
        logger.warning(
            "Symlink not supported or failed (%s); writing latest.txt fallback",
            exc,
        )
        pointer = base / "latest.txt"
        pointer.write_text(f"{rel_target.as_posix()}\n", encoding="utf-8")


def promote_model(task: str, model: str, run_id: str, *, artifacts_root: Path) -> Path:
    """Manually point ``latest`` of ``(task, model)`` at ``<run_id>/final/`` after a gate check.

    Used after ``train --no-promote`` to publish a scheduled run, and to roll ``latest`` back
    to an earlier successful run. ``final/metadata.json`` of the run must exist and carry
    ``status == "ok"``; otherwise ``latest`` is left untouched.

    Args:
        task: Task name (``home_win`` / ``over_5_5``).
        model: Model family (``logreg`` / ``lgbm``).
        run_id: Run to promote, a directory name under ``models/<task>/<model>/``.
        artifacts_root: Root containing ``models/<task>/<model>/<run_id>/final/metadata.json``.

    Returns:
        Path of the promoted ``final/`` directory.

    Raises:
        FileNotFoundError: ``final/metadata.json`` of the run is missing.
        ValueError: The run's ``status`` is not ``ok`` (gate failed; promotion refused).
    """
    final_dir = artifacts_root / "models" / task / model / run_id / "final"
    metadata_path = final_dir / "metadata.json"
    if not metadata_path.is_file():
        raise FileNotFoundError(f"no metadata.json for run {run_id} of {task}/{model}: {metadata_path}")
    status = json.loads(metadata_path.read_text(encoding="utf-8")).get("status")
    if status != "ok":
        raise ValueError(
            f"run {run_id} of {task}/{model} has status={status!r}: the gate was not passed, "
            "promoting it to latest is refused"
        )
    update_latest_symlink(task, model, run_id, artifacts_root=artifacts_root, status="ok")
    return final_dir


def _fit_final_raw_model(
    model_family: str,
    task: str,
    X: pd.DataFrame,
    y_all: np.ndarray,
    final_slices: FinalRetrainSlices,
    config: ResolvedConfig,
    *,
    feature_names: list[str],
    log_loss_fn: Any,
) -> tuple[Any, FitResult | LgbmFitResult]:
    """Select hyperparameters on train_hp + inner_val, then fit raw model on train_full.

    For LGBM the final fit uses a fixed ``num_boost_round`` (the ``best_iteration``
    picked during selection) and no early stopping, since ``inner_val`` ⊂
    ``train_full`` — see :func:`modeling.train_lgbm.train_lgbm_fixed_rounds`.
    """
    hp_tr = final_slices.train_hp_idx
    hp_iv = final_slices.inner_val_idx
    train_full = final_slices.train_full_idx
    y_hp_tr = y_all[hp_tr]
    y_hp_iv = y_all[hp_iv]
    y_train_full = y_all[train_full]

    if model_family == "logreg":
        chosen_C, _pipe, loss_by_C = select_C_by_inner_val(
            X.iloc[hp_tr],
            y_hp_tr,
            X.iloc[hp_iv],
            y_hp_iv,
            list(config.models.logreg.grids.C),
            random_seed=config.random_seed,
            log_loss_fn=log_loss_fn,
        )
        final_pipeline = build_logreg_pipeline(chosen_C, random_seed=config.random_seed)
        final_pipeline.fit(X.iloc[train_full], y_train_full)
        fit: FitResult | LgbmFitResult = FitResult(
            task=task,
            pipeline=final_pipeline,
            chosen_C=chosen_C,
            inner_val_log_loss_by_C=loss_by_C,
            chosen_inner_val_log_loss=loss_by_C[chosen_C],
            n_rows_train=len(train_full),
            n_rows_inner_val=len(hp_iv),
        )
        return final_pipeline, fit

    monotone_spec = getattr(config.models.lgbm.monotone, task)
    monotone = build_monotone_constraints(feature_names, monotone_spec)
    grid = expand_lgbm_grid(config.models.lgbm.grids.model_dump())
    chosen_params, _booster, losses, best_iteration = select_lgbm_config_by_inner_val(
        X.iloc[hp_tr],
        y_hp_tr,
        X.iloc[hp_iv],
        y_hp_iv,
        grid,
        random_seed=config.random_seed,
        num_threads=config.compute.num_threads,
        early_stopping_rounds=LGBM_EARLY_STOPPING_ROUNDS,
        num_boost_round=LGBM_NUM_BOOST_ROUND,
        monotone_constraints=monotone,
        log_loss_fn=log_loss_fn,
    )
    base_params = build_lgbm_base_params(
        random_seed=config.random_seed,
        num_threads=config.compute.num_threads,
        monotone_constraints=monotone,
    )
    full_params = {**base_params, **chosen_params}
    # Fixed-round retrain (UPDATE plan §10): inner_val ⊂ train_full, so early
    # stopping here would validate against rows the model was just fit on and
    # never trigger. num_boost_round is instead pinned to best_iteration, the
    # round count inner-val selection above already chose honestly.
    final_booster = train_lgbm_fixed_rounds(
        X.iloc[train_full],
        y_train_full,
        params=full_params,
        num_boost_round=best_iteration,
    )
    chosen_loss = next(loss for params, loss in losses if params == chosen_params)
    fit = LgbmFitResult(
        task=task,
        booster=final_booster,
        chosen_params=chosen_params,
        inner_val_log_loss_by_config=losses,
        chosen_inner_val_log_loss=chosen_loss,
        best_iteration=best_iteration,
        n_rows_train=len(train_full),
        n_rows_inner_val=len(hp_iv),
    )
    return final_booster, fit


def run_training(
    config: ResolvedConfig,
    *,
    dataset_csv: Path,
    metadata_path: Path,
    task: str = "both",
    model: str = "both",
    run_id: str | None = None,
    dry_run: bool = False,
    artifacts_root: Path | None = None,
    run_start_utc: datetime | None = None,
    fail_on_baseline: bool = True,
    promote: bool = True,
) -> list[RunResult]:
    """Execute per-season checks and the final fit for selected task × model pairs.

    For each ``split.test_seasons`` entry the model trains on all earlier seasons and is
    checked on the whole season; the final model is then fitted on every row. ``home_win``
    is gated against the Elo benchmark (``games_train.csv`` next to
    the dataset, required when ``home_win`` runs), ``over_5_5`` against the constant.

    With ``promote=False`` (CLI ``--no-promote``) the ``latest`` symlink is neither created nor
    moved and its acceptance check is skipped; move it later with :func:`promote_model`.
    """
    if dry_run:
        raise ValueError("use dry_run_training() when dry_run=True")

    artifacts = artifacts_root or Path("artifacts")
    start = run_start_utc or datetime.now(timezone.utc)
    tasks = resolve_tasks(task, config)
    models = resolve_models(model)
    validate_run_id_override(tasks, models, run_id)

    X, keys, labels, _service, metadata = load_training_table_split(dataset_csv, metadata_path)
    X, keys, labels = _sort_frames(X, keys, labels)
    feature_names = list(X.columns)

    splits = build_season_splits(
        keys,
        config.split,
        yaml_reference=config.model_dump(by_alias=True),
        metadata=metadata,
    )
    final_slices = compute_final_retrain_slices(keys, config.split)

    epsilon = config.evaluation.epsilon_clip
    ece_bins = config.evaluation.ece_bins
    metric_fns = standard_metric_fns(epsilon=epsilon)
    elo_by_season: dict[int, _EloSeason] = {}
    if "home_win" in tasks:
        elo_by_season = _fit_elo_seasons(dataset_csv.parent / "games_train.csv", config)
    outcomes: list[_TaskModelOutcome] = []
    results: list[RunResult] = []

    for task_name in tasks:
        y_all = get_task_label(labels, task_name)
        for model_family in models:
            pair_run_id = resolve_run_id(
                task=task_name,
                model=model_family,
                features_hash=config.features_hash,
                run_start_utc=start,
                override=run_id,
            )
            reports_dir = artifacts / "reports" / pair_run_id
            model_run_dir = artifacts / "models" / task_name / model_family / pair_run_id
            run_logger = configure_run_logger(reports_dir, level=config.compute.log_level)
            run_logger.info("Starting training run_id=%s task=%s model=%s", pair_run_id, task_name, model_family)
            run_logger.info("Resolved config:\n%s", json.dumps(config.model_dump(by_alias=True), indent=2))
            run_logger.info("Library versions: %s", _collect_library_versions())

            season_evals: list[_SeasonEval] = []

            for window in splits.windows:
                run_logger.info("Season %d sizes: %s", window.season_id, window.to_log_dict())
                tr, iv, cal, te = (
                    window.train_idx,
                    window.inner_val_idx,
                    window.calibration_idx,
                    window.test_idx,
                )
                y_tr, y_iv, y_cal, y_te = (
                    y_all[tr],
                    y_all[iv],
                    y_all[cal],
                    y_all[te],
                )
                fit = _train_raw_model(
                    model_family,
                    task_name,
                    X.iloc[tr],
                    y_tr,
                    X.iloc[iv],
                    y_iv,
                    config,
                    feature_names=feature_names,
                    log_loss_fn=metric_fns["log_loss"],
                )
                raw_model = _raw_model_from_fit(model_family, fit)
                p_cal_raw = predict_raw_proba(model_family, raw_model, X.iloc[cal])
                calibrator = fit_calibrator(
                    p_cal_raw,
                    y_cal,
                    method=config.calibration.method.value,
                    min_samples=config.calibration.min_samples,
                    seed=config.random_seed,
                    num_threads=config.compute.num_threads,
                )
                p_test_raw = predict_raw_proba(model_family, raw_model, X.iloc[te])
                p_test = apply_calibrator(calibrator, p_test_raw)

                save_calibration_artifact(
                    model_run_dir / f"season_{window.season_id}",
                    model_raw=raw_model,
                    calibrator_fit=calibrator,
                    metadata=_build_season_metadata(
                        model_family=model_family,
                        task=task_name,
                        fit=fit,
                        config=config,
                        window=window,
                        calibrator_fit=calibrator,
                        run_id=pair_run_id,
                    ),
                )

                # Constant benchmark: share of positives over every row before the checked season.
                constant = trivial_baseline(np.concatenate([y_tr, y_iv, y_cal]), y_te, epsilon=epsilon)
                p_const = np.full(len(te), constant["p"])
                elo = elo_by_season.get(window.season_id) if task_name == "home_win" else None
                p_elo_raw, p_elo = (
                    _elo_forecasts(elo, keys.iloc[te]["game_id"].to_numpy(), y_te) if elo else (None, None)
                )
                season_evals.append(
                    _SeasonEval(window, y_te, p_test_raw, p_test, p_const, p_elo_raw, p_elo, elo)
                )

            season_blocks = [
                _season_block(ev, keys, epsilon=epsilon, ece_bins=ece_bins) for ev in season_evals
            ]
            for block in season_blocks:
                run_logger.info("Season %d: %s", block["season_id"], block)

            # Pooled over all checked seasons: same rows for the model, Elo and the constant.
            y_pool = np.concatenate([ev.y for ev in season_evals])
            p_raw_pool = np.concatenate([ev.p_raw for ev in season_evals])
            p_pool = np.concatenate([ev.p_cal for ev in season_evals])
            p_const_pool = np.concatenate([ev.p_const for ev in season_evals])
            has_elo = all(ev.p_elo is not None for ev in season_evals)
            p_elo_pool = np.concatenate([cast("np.ndarray", ev.p_elo) for ev in season_evals]) if has_elo else None
            p_elo_raw_pool = (
                np.concatenate([cast("np.ndarray", ev.p_elo_raw) for ev in season_evals]) if has_elo else None
            )
            pool_keys = keys.iloc[np.concatenate([ev.window.test_idx for ev in season_evals])]
            pool_days = pool_keys["day"]

            model_loss = log_loss_per_game(y_pool, p_pool, epsilon=epsilon)
            diff_ci: dict[str, dict[str, float]] = {}
            benchmarks = {"constant": p_const_pool, **({"elo": p_elo_pool} if p_elo_pool is not None else {})}
            for name, p_other in benchmarks.items():
                ci = bootstrap_mean_diff(
                    model_loss,
                    log_loss_per_game(y_pool, p_other, epsilon=epsilon),
                    pool_days,
                    n_resamples=config.evaluation.bootstrap_samples,
                    seed=config.random_seed,
                )
                diff_ci[f"model_minus_{name}"] = {"point": ci.point, "ci_low": ci.ci_low, "ci_high": ci.ci_high}

            pool_bootstrap = bootstrap_metrics(
                y_pool,
                p_pool,
                day=pool_days,
                block_by_day=True,
                n_resamples=config.evaluation.bootstrap_samples,
                seed=config.random_seed,
                metric_fns=metric_fns,
                num_threads=config.compute.num_threads,
            )
            pooled_block: dict[str, Any] = {
                "n_test": int(len(y_pool)),
                "model_raw": _metrics(y_pool, p_raw_pool, epsilon=epsilon, ece_bins=ece_bins),
                "model": _metrics(y_pool, p_pool, epsilon=epsilon, ece_bins=ece_bins),
                "constant": _metrics(y_pool, p_const_pool, epsilon=epsilon, ece_bins=ece_bins),
                "diff_ci": diff_ci,
                "bootstrap": {name: result.to_dict() for name, result in pool_bootstrap.items()},
                "reliability_path": f"reliability_{task_name}.png",
            }
            calibration_table = {"model": _nonempty_bins(y_pool, p_pool)}
            if p_elo_pool is not None and p_elo_raw_pool is not None:
                pooled_block["elo_raw"] = _metrics(y_pool, p_elo_raw_pool, epsilon=epsilon, ece_bins=ece_bins)
                pooled_block["elo"] = _metrics(y_pool, p_elo_pool, epsilon=epsilon, ece_bins=ece_bins)
                calibration_table["elo"] = _nonempty_bins(y_pool, p_elo_pool)

            slices = _slice_blocks(
                _slice_masks(season_evals, keys, X), y_pool, p_pool, p_const_pool, p_elo_pool, epsilon=epsilon
            )
            team_bd = _team_breakdown_or_empty(y_pool, p_pool, pool_keys, epsilon=epsilon)

            metrics_payload = compose_metrics_json(
                run_id=pair_run_id,
                task=task_name,
                model=model_family,
                features_hash=config.features_hash,
                seasons=season_blocks,
                pooled=pooled_block,
                calibration_table=calibration_table,
                slices=slices,
                team_breakdown=team_bd,
                evaluation={"epsilon_clip": epsilon, "ece_bins": ece_bins},
            )

            # Final retrain on every row: HP on train_hp + inner_val, then fit raw model on train_full.
            final_model, final_fit_full = _fit_final_raw_model(
                model_family,
                task_name,
                X,
                y_all,
                final_slices,
                config,
                feature_names=feature_names,
                log_loss_fn=metric_fns["log_loss"],
            )
            final_calibrator = fit_calibrator(
                predict_raw_proba(model_family, final_model, X.iloc[final_slices.calibration_final_idx]),
                y_all[final_slices.calibration_final_idx],
                method=config.calibration.method.value,
                min_samples=config.calibration.min_samples,
                seed=config.random_seed,
                num_threads=config.compute.num_threads,
            )
            bootstrap_meta = {
                "N": config.evaluation.bootstrap_samples,
                "block_by_day": True,
                "seed": config.random_seed,
            }

            status: RunStatus = "ok"
            summary = f"status: {status}\n\n{compose_summary_md(metrics_payload)}"
            write_report(
                reports_dir,
                metrics_json=metrics_payload,
                reliability_pngs={
                    task_name: reliability_table(y_pool, p_pool, n_bins=ece_bins),
                },
                summary_md=summary,
            )

            final_dir = model_run_dir / "final"
            save_model_artifact(
                final_dir,
                model=final_model,
                metadata=_build_final_metadata(
                    model_family=model_family,
                    task=task_name,
                    fit=final_fit_full,
                    config=config,
                    final_slices=final_slices,
                    calibrator_fit=final_calibrator,
                    run_id=pair_run_id,
                    status=status,
                    bootstrap_meta=bootstrap_meta,
                ),
            )
            joblib.dump(final_calibrator.calibrator, final_dir / "calibrator.joblib")

            benchmark_name = "elo" if p_elo_pool is not None else "constant"
            run_logger.info(
                "Pooled metrics model=%s %s=%s diff_ci=%s",
                pooled_block["model"],
                benchmark_name,
                pooled_block[benchmark_name],
                diff_ci,
            )
            run_logger.info("Artifacts written to %s and %s", model_run_dir, reports_dir)

            pooled_ll = pooled_block["model"]["log_loss"]
            result = RunResult(
                run_id=pair_run_id,
                task=task_name,
                model=model_family,
                status=status,
                exit_code=0,
                reports_dir=reports_dir,
                model_run_dir=model_run_dir,
                pooled_log_loss=pooled_ll,
            )
            outcomes.append(
                _TaskModelOutcome(
                    task=task_name,
                    model=model_family,
                    result=result,
                    pooled_model_log_loss=pooled_ll,
                    benchmark_log_loss=pooled_block[benchmark_name]["log_loss"],
                    benchmark=benchmark_name,
                )
            )
            results.append(result)

    # Acceptance phase 1 (artifacts + baseline); phase 2 (``latest`` symlink) runs below.
    _combined, baseline, _artifacts = apply_acceptance_to_training_outcomes(
        outcomes,
        config=config,
        enabled_tasks=tasks,
        models=models,
        artifacts_root=artifacts,
    )

    for item in outcomes:
        if not fail_on_baseline and item.result.status == "failed_baseline_check":
            item.result.exit_code = 0
        if promote:
            update_latest_symlink(
                item.task,
                item.model,
                item.result.run_id,
                artifacts_root=artifacts,
                status=item.result.status,
            )

    if not promote:
        return results

    # Phase 2: symlinks exist only after update_latest_symlink for status=ok pairs.
    apply_latest_symlink_check(
        outcomes,
        config=config,
        enabled_tasks=tasks,
        models=models,
        artifacts_root=artifacts,
        baseline=baseline,
    )

    return results


def format_dry_run_report(payload: Mapping[str, Any]) -> str:
    """Human-readable dry-run output for CLI stdout."""
    lines = ["=== resolved config ===", json.dumps(payload["config"], indent=2, default=str), ""]
    lines.append("=== task × model matrix ===")
    lines.append(f"tasks: {payload['tasks']}")
    lines.append(f"models: {payload['models']}")
    lines.append("")
    lines.append("=== block sizes (train / inner_val / calibration / test) ===")
    for sizes in payload["block_sizes"]["seasons"]:
        lines.append(
            f"season {sizes['season_id']}: train={sizes['train']} inner_val={sizes['inner_val']} "
            f"calibration={sizes['calibration']} test={sizes['test']}"
        )
    final = payload["block_sizes"]["final_retrain"]
    lines.append(
        f"final_retrain: train={final['train']} inner_val={final['inner_val']} "
        f"calibration={final['calibration']} test={final['test']}"
    )
    lines.append("")
    lines.append("=== final retrain day ranges ===")
    for name, pair in payload["final_retrain_days"].items():
        lines.append(f"{name}: {pair[0]} .. {pair[1]}")
    return "\n".join(lines) + "\n"


__all__ = [
    "RunResult",
    "RunStatus",
    "collect_block_sizes",
    "compute_final_retrain_slices",
    "dry_run_training",
    "format_dry_run_report",
    "resolve_models",
    "resolve_run_id",
    "resolve_tasks",
    "run_training",
    "update_latest_symlink",
    "validate_run_id_override",
]
