"""Training run orchestration for prematch classifiers (UPDATE plan stage 10).

Wires dataset loading, walk-forward splits, model training, calibration,
metrics, bootstrap, artifacts, and reports into one reproducible pipeline.
No PostgreSQL or ``modeling.dataset_builder`` imports.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence

import joblib
import numpy as np
import pandas as pd

from modeling.artifacts import (
    _collect_library_versions,
    _get_git_commit,
    build_lgbm_metadata,
    build_logreg_metadata,
    save_model_artifact,
)
from modeling.bootstrap import bootstrap_metrics, standard_metric_fns
from modeling.calibrate import (
    CalibratorFit,
    apply_calibrator,
    fit_calibrator,
    save_calibration_artifact,
)
from modeling.config import ConfigError, ResolvedConfig, SplitConfig, build_run_id
from modeling.metrics import brier, ece, log_loss, reliability_table, team_breakdown, trivial_baseline
from modeling.acceptance import (
    RunStatus,
    apply_acceptance_to_training_outcomes,
    apply_latest_symlink_check,
)
from modeling.report import compose_metrics_json, compose_summary_md, configure_run_logger, write_report
from modeling.splits import OuterWindow, WalkForwardSplits, build_walk_forward_splits
from modeling.train_common import build_monotone_constraints, expand_lgbm_grid, get_task_label
from modeling.train_input import load_training_table_split
from modeling.train_lgbm import (
    LgbmFitResult,
    build_lgbm_base_params,
    predict_lgbm_proba,
    select_lgbm_config_by_inner_val,
    train_lgbm_for_task,
    train_single_lgbm,
)
from modeling.train_logreg import FitResult, build_logreg_pipeline, select_C_by_inner_val, train_logreg_for_task

logger = logging.getLogger(__name__)

TASK_NAMES: tuple[str, ...] = ("home_win", "over_5_5")
MODEL_FAMILIES: tuple[str, ...] = ("logreg", "lgbm")

LGBM_NUM_BOOST_ROUND = 500
LGBM_EARLY_STOPPING_ROUNDS = 50


@dataclass(frozen=True)
class BlockSizes:
    train: int
    inner_val: int
    calibration: int
    test: int
    holdout: int

    def to_log_dict(self) -> dict[str, int]:
        return {
            "train": self.train,
            "inner_val": self.inner_val,
            "calibration": self.calibration,
            "test": self.test,
            "holdout": self.holdout,
        }


@dataclass(frozen=True)
class FinalRetrainSlices:
    train_full_idx: np.ndarray
    inner_val_idx: np.ndarray
    calibration_final_idx: np.ndarray
    train_full_days: tuple[str, str]
    inner_val_days: tuple[str, str]
    calibration_final_days: tuple[str, str]

    @property
    def train_hp_idx(self) -> np.ndarray:
        if len(self.inner_val_idx) == 0:
            return self.train_full_idx
        cutoff = int(self.inner_val_idx[0])
        return self.train_full_idx[self.train_full_idx < cutoff]


@dataclass
class RunResult:
    run_id: str
    task: str
    model: str
    status: RunStatus
    exit_code: int
    reports_dir: Path
    model_run_dir: Path
    holdout_calibrated_log_loss: float | None = None


@dataclass
class _TaskModelOutcome:
    task: str
    model: str
    result: RunResult
    holdout_calibrated_log_loss: float
    holdout_trivial_log_loss: float


def resolve_tasks(task_flag: str, config: ResolvedConfig) -> list[str]:
    """Map CLI ``--task`` to enabled task names."""
    if task_flag not in (*TASK_NAMES, "both"):
        raise ConfigError(f"unsupported --task {task_flag!r}")
    if task_flag == "both":
        selected = [name for name in TASK_NAMES if getattr(config.tasks, name).enabled]
        if not selected:
            raise ConfigError("no tasks enabled in config")
        return selected
    if not getattr(config.tasks, task_flag).enabled:
        raise ConfigError(
            f"task {task_flag!r} is disabled in config (tasks.{task_flag}.enabled=false) "
            f"but was requested via --task"
        )
    return [task_flag]


def resolve_models(model_flag: str) -> list[str]:
    """Map CLI ``--model`` to model family names."""
    if model_flag not in (*MODEL_FAMILIES, "both"):
        raise ConfigError(f"unsupported --model {model_flag!r}")
    if model_flag == "both":
        return list(MODEL_FAMILIES)
    return [model_flag]


def resolve_run_id(
    *,
    task: str,
    model: str,
    features_hash: str,
    run_start_utc: datetime,
    override: str | None,
) -> str:
    """Return explicit ``--run-id`` or canonical autogenerated id."""
    if override is not None:
        return override
    return build_run_id(task, model, features_hash, run_start_utc)


def validate_run_id_override(
    tasks: Sequence[str],
    models: Sequence[str],
    run_id: str | None,
) -> None:
    """Reject a single ``--run-id`` when it would collide across multiple pairs."""
    if run_id is None:
        return
    pairs = len(tasks) * len(models)
    if pairs > 1:
        raise ConfigError(
            f"--run-id {run_id!r} would be reused for {pairs} (task, model) pairs "
            f"({list(tasks)} × {list(models)}); omit --run-id or restrict "
            f"--task / --model to a single pair"
        )


def _sort_frames(
    X: pd.DataFrame,
    keys: pd.DataFrame,
    labels: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    order = keys.sort_values(["day", "game_id"], kind="mergesort").index
    return (
        X.loc[order].reset_index(drop=True),
        keys.loc[order].reset_index(drop=True),
        labels.loc[order].reset_index(drop=True),
    )


def _day_range_iso(keys: pd.DataFrame, idx: np.ndarray) -> tuple[str, str]:
    if len(idx) == 0:
        return ("", "")
    days = pd.to_datetime(keys.iloc[idx]["day"])
    return (days.min().date().isoformat(), days.max().date().isoformat())


def compute_final_retrain_slices(
    keys: pd.DataFrame,
    splits: WalkForwardSplits,
    config: SplitConfig,
) -> FinalRetrainSlices:
    """Derive ``train_full`` and ``calibration_final`` from walk-forward geometry."""
    wf_mask = np.ones(len(keys), dtype=bool)
    wf_mask[list(splits.holdout.holdout_idx)] = False
    wf_positions = np.flatnonzero(wf_mask)

    if len(wf_positions) < config.calibration_games:
        raise ConfigError(
            "not enough walk-forward rows for calibration_final "
            f"(need {config.calibration_games}, have {len(wf_positions)})"
        )

    calibration_final = wf_positions[-config.calibration_games :]
    train_full = wf_positions[: int(calibration_final[0])]

    if len(train_full) == 0:
        raise ConfigError("train_full is empty after carving calibration_final")

    need_inner = config.inner_val_games
    if len(train_full) < need_inner:
        raise ConfigError(
            "not enough rows in train_full for inner_val_final "
            f"(need {need_inner}, have {len(train_full)})"
        )
    inner_val = train_full[-need_inner:]
    return FinalRetrainSlices(
        train_full_idx=train_full,
        inner_val_idx=inner_val,
        calibration_final_idx=calibration_final,
        train_full_days=_day_range_iso(keys, train_full),
        inner_val_days=_day_range_iso(keys, inner_val),
        calibration_final_days=_day_range_iso(keys, calibration_final),
    )


def collect_block_sizes(
    splits: WalkForwardSplits,
    final_slices: FinalRetrainSlices,
) -> dict[str, Any]:
    """Structured sizes for dry-run logging."""
    fold_sizes = []
    for window in splits.windows:
        fold_sizes.append(
            {
                "k": window.k,
                **BlockSizes(
                    train=window.train_size,
                    inner_val=window.inner_val_size,
                    calibration=window.calibration_size,
                    test=window.test_size,
                    holdout=splits.holdout.holdout_size,
                ).to_log_dict(),
            }
        )
    final_block = BlockSizes(
        train=len(final_slices.train_full_idx),
        inner_val=len(final_slices.inner_val_idx),
        calibration=len(final_slices.calibration_final_idx),
        test=0,
        holdout=splits.holdout.holdout_size,
    )
    return {
        "folds": fold_sizes,
        "final_retrain": final_block.to_log_dict(),
        "holdout": splits.holdout.holdout_size,
    }


def dry_run_training(
    config: ResolvedConfig,
    *,
    dataset_csv: Path,
    metadata_path: Path,
    task_flag: str = "both",
    model_flag: str = "both",
) -> dict[str, Any]:
    """Load data, build splits, return resolved config and block sizes (no training)."""
    _X, keys, _labels, _service, metadata = load_training_table_split(dataset_csv, metadata_path)
    _X, keys, _labels = _sort_frames(_X, keys, _labels)
    splits = build_walk_forward_splits(
        keys,
        config.split,
        yaml_reference=config.model_dump(by_alias=True),
        metadata=metadata,
    )
    final_slices = compute_final_retrain_slices(keys, splits, config.split)
    tasks = resolve_tasks(task_flag, config)
    models = resolve_models(model_flag)
    return {
        "config": config.model_dump(by_alias=True),
        "tasks": tasks,
        "models": models,
        "block_sizes": collect_block_sizes(splits, final_slices),
        "splits_log": splits.to_log_dict(),
        "final_retrain_days": {
            "train_full": final_slices.train_full_days,
            "inner_val": final_slices.inner_val_days,
            "calibration_final": final_slices.calibration_final_days,
            "holdout": _day_range_iso(keys, splits.holdout.holdout_idx),
        },
    }


def _metric_bundle(
    y_true: np.ndarray,
    p_raw: np.ndarray,
    p_cal: np.ndarray | None,
    *,
    y_train_for_baseline: np.ndarray,
    epsilon: float,
    ece_bins: int,
) -> tuple[dict[str, Any], dict[str, Any] | None, dict[str, Any]]:
    raw = {
        "log_loss": log_loss(y_true, p_raw, epsilon=epsilon),
        "brier": brier(y_true, p_raw),
        "ece": ece(y_true, p_raw, n_bins=ece_bins),
    }
    if p_cal is None:
        calibrated = None
    else:
        calibrated = {
            "log_loss": log_loss(y_true, p_cal, epsilon=epsilon),
            "brier": brier(y_true, p_cal),
            "ece": ece(y_true, p_cal, n_bins=ece_bins),
        }
    trivial = trivial_baseline(y_train_for_baseline, y_true, epsilon=epsilon)
    return raw, calibrated, trivial


def _eval_block(
    *,
    k: int | None,
    keys: pd.DataFrame,
    train_idx: np.ndarray,
    test_idx: np.ndarray,
    y_true: np.ndarray,
    p_raw: np.ndarray,
    p_cal: np.ndarray | None,
    y_train_for_baseline: np.ndarray,
    epsilon: float,
    ece_bins: int,
    reliability_path: str | None = None,
) -> dict[str, Any]:
    raw, calibrated, trivial = _metric_bundle(
        y_true,
        p_raw,
        p_cal,
        y_train_for_baseline=y_train_for_baseline,
        epsilon=epsilon,
        ece_bins=ece_bins,
    )
    block: dict[str, Any] = {
        "train_range": {"start": _day_range_iso(keys, train_idx)[0], "end": _day_range_iso(keys, train_idx)[1]},
        "test_range": {"start": _day_range_iso(keys, test_idx)[0], "end": _day_range_iso(keys, test_idx)[1]},
        "n_train": int(len(train_idx)),
        "n_test": int(len(test_idx)),
        "raw": raw,
        "calibrated": calibrated,
        "trivial_base_rate": trivial,
    }
    if k is not None:
        block["k"] = k
    if reliability_path is not None:
        block["reliability_path"] = reliability_path
    return block


def _predict_raw(model_family: str, model: Any, X: pd.DataFrame) -> np.ndarray:
    if model_family == "logreg":
        return model.predict_proba(X)[:, 1]
    return predict_lgbm_proba(model, X)


def _train_raw_model(
    model_family: str,
    task: str,
    X_train: pd.DataFrame,
    y_train: np.ndarray,
    X_val: pd.DataFrame,
    y_val: np.ndarray,
    config: ResolvedConfig,
    *,
    feature_names: list[str],
    log_loss_fn: Any,
) -> FitResult | LgbmFitResult:
    seed = config.random_seed
    if model_family == "logreg":
        return train_logreg_for_task(
            task,
            X_train,
            y_train,
            X_val,
            y_val,
            C_grid=list(config.models.logreg.grids.C),
            random_seed=seed,
            log_loss_fn=log_loss_fn,
        )
    monotone_spec = getattr(config.models.lgbm.monotone, task)
    monotone = build_monotone_constraints(feature_names, monotone_spec)
    grid = expand_lgbm_grid(config.models.lgbm.grids.model_dump())
    return train_lgbm_for_task(
        task,
        X_train,
        y_train,
        X_val,
        y_val,
        grid=grid,
        random_seed=seed,
        num_threads=config.compute.num_threads,
        early_stopping_rounds=LGBM_EARLY_STOPPING_ROUNDS,
        num_boost_round=LGBM_NUM_BOOST_ROUND,
        log_loss_fn=log_loss_fn,
        monotone_constraints=monotone,
    )


def _raw_model_from_fit(model_family: str, fit: FitResult | LgbmFitResult) -> Any:
    if model_family == "logreg":
        assert isinstance(fit, FitResult)
        return fit.pipeline
    assert isinstance(fit, LgbmFitResult)
    return fit.booster


def _build_fold_metadata(
    *,
    model_family: str,
    task: str,
    fit: FitResult | LgbmFitResult,
    config: ResolvedConfig,
    window: OuterWindow,
    calibrator_fit: CalibratorFit,
    run_id: str,
) -> dict[str, Any]:
    train_days = (
        window.train_days.min_day.date().isoformat(),
        window.train_days.max_day.date().isoformat(),
    )
    inner_days = (
        window.inner_val_days.min_day.date().isoformat(),
        window.inner_val_days.max_day.date().isoformat(),
    )
    cal_days = (
        window.calibration_days.min_day.date().isoformat(),
        window.calibration_days.max_day.date().isoformat(),
    )
    common = {
        "run_id": run_id,
        "task": task,
        "fold_k": window.k,
        "random_seed": config.random_seed,
        "features_hash": config.features_hash,
        "feature_set_version": config.feature_set_version,
        "feature_manifest": config.feature_manifest,
        "train_days": {"min": train_days[0], "max": train_days[1]},
        "inner_val_days": {"min": inner_days[0], "max": inner_days[1]},
        "calibration_days": {"min": cal_days[0], "max": cal_days[1]},
        "n_rows_train": fit.n_rows_train,
        "n_rows_inner_val": fit.n_rows_inner_val,
        "n_rows_calibration": calibrator_fit.n_calibration,
    }
    if model_family == "logreg":
        assert isinstance(fit, FitResult)
        meta = build_logreg_metadata(
            task=task,
            chosen_C=fit.chosen_C,
            class_weight=None,
            random_seed=config.random_seed,
            features_hash=config.features_hash,
            feature_set_version=config.feature_set_version,
            feature_manifest=config.feature_manifest,
            n_rows_train=fit.n_rows_train,
            n_rows_inner_val=fit.n_rows_inner_val,
            train_days=train_days,
            inner_val_days=inner_days,
            calibration_days=cal_days,
            run_id=run_id,
        )
    else:
        assert isinstance(fit, LgbmFitResult)
        meta = build_lgbm_metadata(
            task=task,
            chosen_params=fit.chosen_params,
            best_iteration=fit.best_iteration,
            random_seed=config.random_seed,
            features_hash=config.features_hash,
            feature_set_version=config.feature_set_version,
            feature_manifest=config.feature_manifest,
            n_rows_train=fit.n_rows_train,
            n_rows_inner_val=fit.n_rows_inner_val,
            train_days=train_days,
            inner_val_days=inner_days,
            calibration_days=cal_days,
            run_id=run_id,
        )
    meta.update(common)
    meta["model_family"] = model_family
    return meta


def _build_final_metadata(
    *,
    model_family: str,
    task: str,
    fit: FitResult | LgbmFitResult,
    config: ResolvedConfig,
    final_slices: FinalRetrainSlices,
    splits: WalkForwardSplits,
    keys: pd.DataFrame,
    calibrator_fit: CalibratorFit,
    run_id: str,
    status: RunStatus,
    bootstrap_meta: dict[str, Any],
) -> dict[str, Any]:
    train_days = final_slices.train_full_days
    inner_days = final_slices.inner_val_days
    cal_days = final_slices.calibration_final_days
    holdout_days = _day_range_iso(keys, splits.holdout.holdout_idx)
    meta: dict[str, Any] = {
        "run_id": run_id,
        "task": task,
        "model_family": model_family,
        "status": status,
        "random_seed": config.random_seed,
        "features_hash": config.features_hash,
        "feature_set_version": config.feature_set_version,
        "feature_manifest": config.feature_manifest,
        "train_days": {"min": train_days[0], "max": train_days[1]},
        "inner_val_days": {"min": inner_days[0], "max": inner_days[1]},
        "calibration_days": {"min": cal_days[0], "max": cal_days[1]},
        "test_days": None,
        "holdout_days": {"min": holdout_days[0], "max": holdout_days[1]},
        "n_rows_train": len(final_slices.train_full_idx),
        "n_rows_inner_val": len(final_slices.inner_val_idx),
        "n_rows_calibration": calibrator_fit.n_calibration,
        "n_rows_test": 0,
        "n_rows_holdout": splits.holdout.holdout_size,
        "bootstrap": bootstrap_meta,
        "library_versions": _collect_library_versions(),
        "git_commit": _get_git_commit(),
    }
    if model_family == "logreg":
        assert isinstance(fit, FitResult)
        meta["chosen_C"] = fit.chosen_C
        meta["class_weight"] = None
    else:
        assert isinstance(fit, LgbmFitResult)
        meta["chosen_params"] = fit.chosen_params
        meta["best_iteration"] = fit.best_iteration
    meta.update(calibrator_fit.to_dict())
    return meta


def _team_breakdown_or_empty(
    y_true: np.ndarray,
    p_eval: np.ndarray,
    keys: pd.DataFrame,
    *,
    epsilon: float,
) -> dict[str, list[dict[str, Any]] | pd.DataFrame]:
    out: dict[str, list[dict[str, Any]] | pd.DataFrame] = {}
    for col in ("home_team_id", "away_team_id"):
        if col not in keys.columns:
            out[col] = []
            continue
        frame = team_breakdown(
            y_true,
            p_eval,
            team_ids=keys[col].to_numpy(),
            by=col,  # type: ignore[arg-type]
            epsilon=epsilon,
        )
        out[col] = frame
    return out


def update_latest_symlink(
    task: str,
    model: str,
    run_id: str,
    *,
    artifacts_root: Path,
    status: RunStatus,
) -> None:
    """Atomically point ``artifacts/models/<task>/<model>/latest`` at ``<run_id>/final/``.

    Skipped when ``status != ok``. On filesystems without symlink support, writes
    ``latest.txt`` with the relative target path instead of raising.
    """
    if status != "ok":
        logger.info(
            "Skipping latest symlink for %s/%s run %s (status=%s)",
            task,
            model,
            run_id,
            status,
        )
        return

    base = artifacts_root / "models" / task / model
    base.mkdir(parents=True, exist_ok=True)
    rel_target = Path(run_id) / "final"
    link_path = base / "latest"
    tmp_link = base / f".latest_tmp_{run_id}"

    try:
        if tmp_link.exists() or tmp_link.is_symlink():
            tmp_link.unlink()
        os.symlink(rel_target, tmp_link)
        os.replace(tmp_link, link_path)
        logger.info("Updated latest symlink → %s", rel_target)
    except OSError as exc:
        logger.warning(
            "Symlink not supported or failed (%s); writing latest.txt fallback",
            exc,
        )
        pointer = base / "latest.txt"
        pointer.write_text(f"{rel_target.as_posix()}\n", encoding="utf-8")


def _fit_final_raw_model(
    model_family: str,
    task: str,
    X: pd.DataFrame,
    y_all: np.ndarray,
    final_slices: FinalRetrainSlices,
    config: ResolvedConfig,
    *,
    feature_names: list[str],
    log_loss_fn: Any,
) -> tuple[Any, FitResult | LgbmFitResult]:
    """Select hyperparameters on train_hp + inner_val, then fit raw model on train_full."""
    hp_tr = final_slices.train_hp_idx
    hp_iv = final_slices.inner_val_idx
    train_full = final_slices.train_full_idx
    y_hp_tr = y_all[hp_tr]
    y_hp_iv = y_all[hp_iv]
    y_train_full = y_all[train_full]

    if model_family == "logreg":
        chosen_C, _pipe, loss_by_C = select_C_by_inner_val(
            X.iloc[hp_tr],
            y_hp_tr,
            X.iloc[hp_iv],
            y_hp_iv,
            list(config.models.logreg.grids.C),
            random_seed=config.random_seed,
            log_loss_fn=log_loss_fn,
        )
        final_pipeline = build_logreg_pipeline(chosen_C, random_seed=config.random_seed)
        final_pipeline.fit(X.iloc[train_full], y_train_full)
        fit: FitResult | LgbmFitResult = FitResult(
            task=task,
            pipeline=final_pipeline,
            chosen_C=chosen_C,
            inner_val_log_loss_by_C=loss_by_C,
            chosen_inner_val_log_loss=loss_by_C[chosen_C],
            n_rows_train=len(train_full),
            n_rows_inner_val=len(hp_iv),
        )
        return final_pipeline, fit

    monotone_spec = getattr(config.models.lgbm.monotone, task)
    monotone = build_monotone_constraints(feature_names, monotone_spec)
    grid = expand_lgbm_grid(config.models.lgbm.grids.model_dump())
    chosen_params, _booster, losses, best_iteration = select_lgbm_config_by_inner_val(
        X.iloc[hp_tr],
        y_hp_tr,
        X.iloc[hp_iv],
        y_hp_iv,
        grid,
        random_seed=config.random_seed,
        num_threads=config.compute.num_threads,
        early_stopping_rounds=LGBM_EARLY_STOPPING_ROUNDS,
        num_boost_round=LGBM_NUM_BOOST_ROUND,
        monotone_constraints=monotone,
        log_loss_fn=log_loss_fn,
    )
    base_params = build_lgbm_base_params(
        random_seed=config.random_seed,
        num_threads=config.compute.num_threads,
        monotone_constraints=monotone,
    )
    full_params = {**base_params, **chosen_params}
    final_booster = train_single_lgbm(
        X.iloc[train_full],
        y_train_full,
        X.iloc[hp_iv],
        y_hp_iv,
        params=full_params,
        num_boost_round=LGBM_NUM_BOOST_ROUND,
        early_stopping_rounds=LGBM_EARLY_STOPPING_ROUNDS,
    )
    chosen_loss = next(loss for params, loss in losses if params == chosen_params)
    fit = LgbmFitResult(
        task=task,
        booster=final_booster,
        chosen_params=chosen_params,
        inner_val_log_loss_by_config=losses,
        chosen_inner_val_log_loss=chosen_loss,
        best_iteration=final_booster.best_iteration,
        n_rows_train=len(train_full),
        n_rows_inner_val=len(hp_iv),
    )
    return final_booster, fit


def run_training(
    config: ResolvedConfig,
    *,
    dataset_csv: Path,
    metadata_path: Path,
    task: str = "both",
    model: str = "both",
    run_id: str | None = None,
    dry_run: bool = False,
    artifacts_root: Path | None = None,
    run_start_utc: datetime | None = None,
    fail_on_baseline: bool = True,
) -> list[RunResult]:
    """Execute walk-forward training for selected task × model pairs."""
    if dry_run:
        raise ValueError("use dry_run_training() when dry_run=True")

    artifacts = artifacts_root or Path("artifacts")
    start = run_start_utc or datetime.now(timezone.utc)
    tasks = resolve_tasks(task, config)
    models = resolve_models(model)
    validate_run_id_override(tasks, models, run_id)

    X, keys, labels, _service, metadata = load_training_table_split(dataset_csv, metadata_path)
    X, keys, labels = _sort_frames(X, keys, labels)
    feature_names = list(X.columns)

    splits = build_walk_forward_splits(
        keys,
        config.split,
        yaml_reference=config.model_dump(by_alias=True),
        metadata=metadata,
    )
    final_slices = compute_final_retrain_slices(keys, splits, config.split)

    metric_fns = standard_metric_fns(epsilon=config.evaluation.epsilon_clip)
    outcomes: list[_TaskModelOutcome] = []
    results: list[RunResult] = []

    for task_name in tasks:
        y_all = get_task_label(labels, task_name)
        for model_family in models:
            pair_run_id = resolve_run_id(
                task=task_name,
                model=model_family,
                features_hash=config.features_hash,
                run_start_utc=start,
                override=run_id,
            )
            reports_dir = artifacts / "reports" / pair_run_id
            model_run_dir = artifacts / "models" / task_name / model_family / pair_run_id
            run_logger = configure_run_logger(reports_dir, level=config.compute.log_level)
            run_logger.info("Starting training run_id=%s task=%s model=%s", pair_run_id, task_name, model_family)
            run_logger.info("Resolved config:\n%s", json.dumps(config.model_dump(by_alias=True), indent=2))
            run_logger.info("Library versions: %s", _collect_library_versions())

            fold_blocks: list[dict[str, Any]] = []

            for window in splits.windows:
                run_logger.info("Fold k=%d sizes: %s", window.k, window.to_log_dict())
                tr, iv, cal, te = (
                    window.train_idx,
                    window.inner_val_idx,
                    window.calibration_idx,
                    window.test_idx,
                )
                y_tr, y_iv, y_cal, y_te = (
                    y_all[tr],
                    y_all[iv],
                    y_all[cal],
                    y_all[te],
                )
                fit = _train_raw_model(
                    model_family,
                    task_name,
                    X.iloc[tr],
                    y_tr,
                    X.iloc[iv],
                    y_iv,
                    config,
                    feature_names=feature_names,
                    log_loss_fn=metric_fns["log_loss"],
                )
                raw_model = _raw_model_from_fit(model_family, fit)
                p_cal_raw = _predict_raw(model_family, raw_model, X.iloc[cal])
                calibrator = fit_calibrator(
                    p_cal_raw,
                    y_cal,
                    method=config.calibration.method.value,
                    min_samples=config.calibration.min_samples,
                    seed=config.random_seed,
                    num_threads=config.compute.num_threads,
                )
                p_test_raw = _predict_raw(model_family, raw_model, X.iloc[te])
                p_test = apply_calibrator(calibrator, p_test_raw)

                fold_dir = model_run_dir / f"fold_{window.k}"
                save_calibration_artifact(
                    fold_dir,
                    model_raw=raw_model,
                    calibrator_fit=calibrator,
                    metadata=_build_fold_metadata(
                        model_family=model_family,
                        task=task_name,
                        fit=fit,
                        config=config,
                        window=window,
                        calibrator_fit=calibrator,
                        run_id=pair_run_id,
                    ),
                )

                bootstrap = bootstrap_metrics(
                    y_te,
                    p_test,
                    block_by_day=False,
                    n_resamples=config.evaluation.bootstrap_samples,
                    seed=config.random_seed,
                    metric_fns=metric_fns,
                    num_threads=config.compute.num_threads,
                )
                run_logger.info(
                    "Fold k=%d bootstrap log_loss: %s",
                    window.k,
                    bootstrap["log_loss"].to_dict(),
                )

                fold_blocks.append(
                    _eval_block(
                        k=window.k,
                        keys=keys,
                        train_idx=tr,
                        test_idx=te,
                        y_true=y_te,
                        p_raw=p_test_raw,
                        p_cal=p_test,
                        y_train_for_baseline=y_tr,
                        epsilon=config.evaluation.epsilon_clip,
                        ece_bins=config.evaluation.ece_bins,
                    )
                )

            # Final retrain: HP on train_hp + inner_val, then fit raw model on train_full.
            y_train_full = y_all[final_slices.train_full_idx]
            final_model, final_fit_full = _fit_final_raw_model(
                model_family,
                task_name,
                X,
                y_all,
                final_slices,
                config,
                feature_names=feature_names,
                log_loss_fn=metric_fns["log_loss"],
            )

            y_cal_final = y_all[final_slices.calibration_final_idx]
            p_cal_final_raw = _predict_raw(
                model_family,
                final_model,
                X.iloc[final_slices.calibration_final_idx],
            )
            final_calibrator = fit_calibrator(
                p_cal_final_raw,
                y_cal_final,
                method=config.calibration.method.value,
                min_samples=config.calibration.min_samples,
                seed=config.random_seed,
                num_threads=config.compute.num_threads,
            )

            holdout_idx = splits.holdout.holdout_idx
            y_holdout = y_all[holdout_idx]
            p_holdout_raw = _predict_raw(model_family, final_model, X.iloc[holdout_idx])
            p_holdout = apply_calibrator(final_calibrator, p_holdout_raw)
            holdout_keys = keys.iloc[holdout_idx]

            holdout_bootstrap = bootstrap_metrics(
                y_holdout,
                p_holdout,
                day=holdout_keys["day"],
                block_by_day=True,
                n_resamples=config.evaluation.bootstrap_samples,
                seed=config.random_seed,
                metric_fns=metric_fns,
                num_threads=config.compute.num_threads,
            )
            bootstrap_meta = {
                "N": config.evaluation.bootstrap_samples,
                "block_by_day": True,
                "seed": config.random_seed,
            }

            holdout_block = _eval_block(
                k=None,
                keys=keys,
                train_idx=final_slices.train_full_idx,
                test_idx=holdout_idx,
                y_true=y_holdout,
                p_raw=p_holdout_raw,
                p_cal=p_holdout,
                y_train_for_baseline=y_train_full,
                epsilon=config.evaluation.epsilon_clip,
                ece_bins=config.evaluation.ece_bins,
                reliability_path=f"reliability_{task_name}.png",
            )
            holdout_block["bootstrap"] = {
                name: result.to_dict() for name, result in holdout_bootstrap.items()
            }

            team_bd = _team_breakdown_or_empty(
                y_holdout,
                p_holdout,
                holdout_keys,
                epsilon=config.evaluation.epsilon_clip,
            )

            metrics_payload = compose_metrics_json(
                run_id=pair_run_id,
                task=task_name,
                model=model_family,
                features_hash=config.features_hash,
                folds=fold_blocks,
                holdout=holdout_block,
                team_breakdown=team_bd,
                evaluation={
                    "epsilon_clip": config.evaluation.epsilon_clip,
                    "ece_bins": config.evaluation.ece_bins,
                },
            )

            status: RunStatus = "ok"
            holdout_cal_ll = holdout_block["calibrated"]["log_loss"]
            holdout_trivial_ll = holdout_block["trivial_base_rate"]["log_loss"]

            summary = f"status: {status}\n\n{compose_summary_md(metrics_payload)}"
            rel_df = reliability_table(
                y_holdout,
                p_holdout,
                n_bins=config.evaluation.ece_bins,
            )
            write_report(
                reports_dir,
                metrics_json=metrics_payload,
                reliability_pngs={task_name: rel_df},
                summary_md=summary,
            )

            final_dir = model_run_dir / "final"
            save_model_artifact(
                final_dir,
                model=final_model,
                metadata=_build_final_metadata(
                    model_family=model_family,
                    task=task_name,
                    fit=final_fit_full,
                    config=config,
                    final_slices=final_slices,
                    splits=splits,
                    keys=keys,
                    calibrator_fit=final_calibrator,
                    run_id=pair_run_id,
                    status=status,
                    bootstrap_meta=bootstrap_meta,
                ),
            )
            joblib.dump(final_calibrator.calibrator, final_dir / "calibrator.joblib")

            run_logger.info(
                "Holdout metrics raw=%s calibrated=%s trivial=%s bootstrap=%s",
                holdout_block["raw"],
                holdout_block["calibrated"],
                holdout_block["trivial_base_rate"],
                {k: v.to_dict() for k, v in holdout_bootstrap.items()},
            )
            run_logger.info("Artifacts written to %s and %s", model_run_dir, reports_dir)

            result = RunResult(
                run_id=pair_run_id,
                task=task_name,
                model=model_family,
                status=status,
                exit_code=0,
                reports_dir=reports_dir,
                model_run_dir=model_run_dir,
                holdout_calibrated_log_loss=holdout_cal_ll,
            )
            outcomes.append(
                _TaskModelOutcome(
                    task=task_name,
                    model=model_family,
                    result=result,
                    holdout_calibrated_log_loss=holdout_cal_ll,
                    holdout_trivial_log_loss=holdout_trivial_ll,
                )
            )
            results.append(result)

    # Acceptance phase 1 (artifacts + baseline); phase 2 (``latest`` symlink) runs below.
    _combined, baseline, _artifacts = apply_acceptance_to_training_outcomes(
        outcomes,
        config=config,
        enabled_tasks=tasks,
        models=models,
        artifacts_root=artifacts,
    )

    for item in outcomes:
        if not fail_on_baseline and item.result.status == "failed_baseline_check":
            item.result.exit_code = 0
        update_latest_symlink(
            item.task,
            item.model,
            item.result.run_id,
            artifacts_root=artifacts,
            status=item.result.status,
        )

    # Phase 2: symlinks exist only after update_latest_symlink for status=ok pairs.
    apply_latest_symlink_check(
        outcomes,
        config=config,
        enabled_tasks=tasks,
        models=models,
        artifacts_root=artifacts,
        baseline=baseline,
    )

    return results


def format_dry_run_report(payload: Mapping[str, Any]) -> str:
    """Human-readable dry-run output for CLI stdout."""
    lines = ["=== resolved config ===", json.dumps(payload["config"], indent=2, default=str), ""]
    lines.append("=== task × model matrix ===")
    lines.append(f"tasks: {payload['tasks']}")
    lines.append(f"models: {payload['models']}")
    lines.append("")
    lines.append("=== block sizes (train / inner_val / calibration / test / holdout) ===")
    for fold in payload["block_sizes"]["folds"]:
        sizes = fold
        lines.append(
            f"fold k={fold['k']}: train={sizes['train']} inner_val={sizes['inner_val']} "
            f"calibration={sizes['calibration']} test={sizes['test']} holdout={sizes['holdout']}"
        )
    final = payload["block_sizes"]["final_retrain"]
    lines.append(
        f"final_retrain: train={final['train']} inner_val={final['inner_val']} "
        f"calibration={final['calibration']} test={final['test']} holdout={final['holdout']}"
    )
    lines.append("")
    lines.append("=== final retrain day ranges ===")
    for name, pair in payload["final_retrain_days"].items():
        lines.append(f"{name}: {pair[0]} .. {pair[1]}")
    return "\n".join(lines) + "\n"


__all__ = [
    "RunResult",
    "RunStatus",
    "collect_block_sizes",
    "compute_final_retrain_slices",
    "dry_run_training",
    "format_dry_run_report",
    "resolve_models",
    "resolve_run_id",
    "resolve_tasks",
    "run_training",
    "update_latest_symlink",
    "validate_run_id_override",
]
