CREATE TABLE game_player_stats(
    team_id                     bigint NOT NULL,
    game_id                     bigint NOT NULL,
    player_id                   bigint NOT NULL,
    time_on_ice                 varchar(10),
    assists                     int,
    goals                       int,
    shots                       int,
    hits                        int,
    power_play_goals            int,
    power_play_assists          int,
    penalty_minutes             int,
    face_off_wins               int,
    face_off_taken              int,
    takeaways                   int,
    giveaways                   int,
    short_handed_goals          int,
    short_handed_assists        int,
    blocked                     int,
    plus_minus                  int,
    face_off_pct                double precision,
    UNIQUE (game_id, player_id)
);
