create table players_season_stats(
    time_on_ice                             varchar(20),
    assists                                 int,
    goals                                   int,
    pim                                     int,
    shots                                   int,
    games                                   int,
    hits                                    int,
    power_play_goals                        int,
    power_play_points                       int,
    power_play_time_on_ice                  varchar(20),
    even_time_on_ice                        varchar(20),
    penalty_minutes                         int,
    face_off_pct                            double PRECISION,
    shot_pct                                double PRECISION,
    game_winning_goals                      int,
    over_time_goals                         int,
    short_handed_goals                      int,
    short_handed_points                     int,
    short_handed_time_on_ice                varchar(20),
    blocked                                 int,
    plus_minus                              int,
    points                                  int,
    shifts                                  int,
    time_on_ice_per_game                    varchar(20),
    even_time_on_ice_per_game               varchar(20),
    short_handed_time_on_ice_per_game       varchar(20),
    power_play_time_on_ice_per_game         varchar(20),
    player_id                               int
);